routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login',[AuthController::class, 'login'])->name('login');
Route::get('forgot_password',[AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::post('login/logon',[AuthController::class, 'logon'])->name('logon');
Route::get('logout',[AuthController::class, 'logout'])->name('logout');
Route::put('first_login',[AuthController::class, 'firstLogin'])->name('first.login');
Route::get('changePassword',[AuthController::class, 'changerPassword'])->name('change.password');
Route::put('changedPassword',[AuthController::class, 'changedPassword'])->name('changed.password');
Route::get('login/first_login',[AuthController::class, 'changedFirstLogin'])->name('form.first.login');
Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('user/List',[UserController::class, 'viewByUser'])->name('view.by.user');
    Route::middleware(['is.admin:0'])->group(function () {
        Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');
        Route::get('user/listSoftDelete',[UserController::class, 'listSoftDelete'])->name('user.list.soft.delete');
        Route::get('user/restore/{id}',[UserController::class, 'restore'])->name('user.restore');
        Route::delete('user/deleteOver/{id}',[UserController::class, 'deleteOver'])->name('user.delete.over');
        Route::resource('user',UserController::class);
        Route::resource('role',RoleController::class);
        Route::resource('position',PositionController::class);
        Route::resource('department',DepartmentController::class);
    }); 
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;
    protected $table = 'roles';
    public $timestamps = false;
    protected $fillable = [
        'name',
    ];
    
    public function users(){
        return $this->hasMany(User::class, 'role_id', 'id');
    }

    public function userss()
    {
        return $this->hasMany('App\Models\User', 'role_id', 'id');
    }
    
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\UpdateRoleRequest;
use App\Models\Role;
use GuzzleHttp\Promise\Create;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $role;
    public function __construct(Role $role)
    {
        $this->role= $role;
    }
    public function index()
    {
        $data = $this->role->all();
        return view('admin.roles.index',[
            'title' => 'List Role',
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create',[
            'title' => 'Danh sách Role',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateRoleRequest $request)
    {   
        if($this->role->create($request->all())) {
            return redirect(route('role.index'))->with('success', 'Tạo thành công Role : ' . $request->name);
        }
        return redirect()->back()->with('error', "Có lỗi trong quá trình tạo");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = $this->role->find($id); 
        return view('admin.roles.update',[
            'title' => 'Edit Role',
            'role' => $role,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, $id)
    {
        if($this->role->find($id)->update($request->all())) {
            return redirect(route('role.index'))->with('success', 'Update thành công Role : ' . $request->name);
        }
        return redirect()->back()->with('error', "Có lỗi trong quá trình Update");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = $this->role->find($id);
        $role->delete();
        return redirect()->back()->with('success', 'Xóa thành công');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('role.index') }}">Role</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('content')
    @include('layouts.alert')
    <form action="{{ route('role.store') }}" method="post">
        @csrf
        @include('layouts.label_form', [
            'label' => 'Role Name',
            'name' => 'name',
            'placeholder' => 'Mời bạn nhập Tên Role ...',
            'value' => old('name'),
        ])
        <button type="submit" name="addRole" class="btn btn-primary">Thêm Role</button>
    </form>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active">Role</li>
@endsection

@section('content')
    <div>
        @include('layouts.alert')
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $role)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $role->name }}</td>
                        <td>
                            <div class="row">
                                <a href="{{ route('role.edit', $role->id) }}" class="btn btn-warning"><i
                                        class="fa fa-edit"></i></a> &ensp;
                                <form action="{{ route('role.destroy', $role->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                        <i class="fa fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/roles/update.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('role.index') }}">Role</a></li>
    <li class="breadcrumb-item active">Update</li>
@endsection

@section('content')
    <form action="{{ route('role.update', $role->id) }}" method="post">
        @csrf
        @method('put')
        @include('layouts.label_form', [
            'label' => 'Role Name',
            'name' => 'name',
            'placeholder' => 'Mời bạn nhập Tên Role ...',
            'value' => $role->name,
        ])
        <button type="submit" name="addRole" class="btn btn-primary">Sửa Role</button>
    </form>
@endsection