routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login',[AuthController::class, 'login'])->name('login');
Route::get('forgot_password',[AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::post('login/logon',[AuthController::class, 'logon'])->name('logon');
Route::get('logout',[AuthController::class, 'logout'])->name('logout');
Route::put('first_login',[AuthController::class, 'firstLogin'])->name('first.login');
Route::get('changePassword',[AuthController::class, 'changerPassword'])->name('change.password');
Route::put('changedPassword',[AuthController::class, 'changedPassword'])->name('changed.password');
Route::get('login/first_login',[AuthController::class, 'changedFirstLogin'])->name('form.first.login');
Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('user/List',[UserController::class, 'viewByUser'])->name('view.by.user');
    Route::middleware(['is.admin:0'])->group(function () {
        Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');
        Route::get('user/listSoftDelete',[UserController::class, 'listSoftDelete'])->name('user.list.soft.delete');
        Route::get('user/restore/{id}',[UserController::class, 'restore'])->name('user.restore');
        Route::delete('user/deleteOver/{id}',[UserController::class, 'deleteOver'])->name('user.delete.over');
        Route::resource('user',UserController::class);
        Route::resource('role',RoleController::class);
        Route::resource('position',PositionController::class);
        Route::resource('department',DepartmentController::class);
    }); 
});

app/Models/User.php
<?php

namespace App\Models;
use Illuminate\Support\Facades\Hash;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\Mail;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'user',
        'email',
        'gender',
        'first_login',
        'role_id',
        'department_id',
        'position_id',
        'address',
        'action',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function department(){
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function role(){
        return $this->belongsTo(Role::class, 'role_id', 'id');
    }

    public function position(){
        return $this->belongsTo(Position::class, 'position_id', 'id');
    }

    public function changePasswords(){
        return $this->hasMany(ChangePassword::class, 'user_id', 'id');
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    public function scopeSearchUser($query)
    {
        if ($search = request()->search) {
            $query = $query->where('name', 'like', '%' . $search . '%');
        }
        return $query;
    }

    public function scopeActionUser($query)
    {
        if (isset(request()->action) && request()->action != null) {
            $query = $query->where('action', request()->action);
        }
        return $query;
    }

    public function sendMail($blade,$token,$check){ 
        Mail::send(
            $blade,
            compact(['check','token']),
            function ($message) use ($check) {
                $message->to($check->email, $check->name);
                $message->subject('Reset mật khẩu');
            }
        );
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\StoreUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Models\Department;
use App\Models\Position;
use App\Models\User;
use App\Models\Role;
use Illuminate\Support\Facades\Auth;
use App\Exports\UsersExport;
use Maatwebsite\Excel\Facades\Excel;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $user;
    private $role;
    private $department;
    private $position;
    public function __construct(User $user , Role $role , Department $department, Position $position)
    {
        $this->user=$user;
        $this->role=$role;
        $this->department=$department;
        $this->position=$position;
    }

    public function index()
    {
        $offset = 6;
        $data= $this->user->with(['role', 'department', 'position', 'changePasswords'])->SearchUser()->ActionUser(); 
        $count = $data->count();
        $data= $data->paginate($offset);
        return view('admin.users.index',[
            'title' => 'List User',
            'topTitle' => 'Danh Sách nhân viên ('.$count.')',
            'data' => $data,
            'offset' => $offset
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles= $this->role->all();
        $positions= $this->position->all();
        $departments= $this->department->all(); 
        $data=[ 
            'roles' =>  $roles,
            'positions' => $positions, 
            'departments' =>  $departments,
        ]; 
        return view('admin.users.create',[
            'title' => 'Create User',
            'topTitle' => 'Tạo nhân viên mới',
            'data' => $data,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        if($this->user->create($request->all())) {
            return redirect(route('user.index'))->with('success','Tạo thành công user : '. $request->name);
        }
        return redirect()->back()->with('error','Tạo user không thành công ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles= $this->role->all();
        $positions= $this->position->all();
        $departments= $this->department->all(); 
        $data=[ 
            'roles' =>  $roles,
            'positions' => $positions, 
            'departments' =>  $departments,
        ]; 
       $user = $this->user->find($id);
       return view('admin.users.update',[
        'title' => 'Sửa user',
        'topTitle' => 'Sửa User',
        'user' => $user,
        'data'=> $data
       ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $user= $this->user->find($id); 
        $user->update(
            $request->all()
        ); 
        if(isset($request->password)) {
            $user->update([
                'password' => $request ->password
            ]);
        }
        return redirect(route('user.index'))->with('success','Sửa thành công user : '. $request->name);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->user->find($id);
        $user->delete();
        return redirect()->back()->with('success', 'Xóa thành công user : '.$user->name);
    }
    public function listSoftDelete()
    {
        $data = $this->user->onlyTrashed()->get();
        return view('admin.users.list_delete', [
            'title' => 'Danh sách xóa mềm',
            'topTitle' => 'Danh sách xóa mềm',
            'data' => $data,
        ]);
    }
    public function restore($id)
    {
        $user = $this->user->onlyTrashed()->where('id', $id)->first();
        $user->restore();
        return redirect()->back()->with('success', 'Đã restore user : '. $user->name);
    }
    public function deleteOver($id)
    {
        $user = $this->user->onlyTrashed()->where('id', $id)->first();
        $user->ForceDelete();
        return redirect()->back()->with('success', 'Đã xóa user khỏi database ');
    }
    public function viewByUser()
    {
        $user = Auth::user();
        $users = $this->user->with(['role', 'department', 'position', 'changePasswords'])->ActionUser()
        ->join('positions','positions.id','users.position_id')
        ->where('positions.pority', '>=', $user->position->pority)
        ->where('department_id', $user->department_id)
        ->get();
       return view('admin.users.view_user',[
        'title' => 'Xem danh sách',
        'topTitle' => 'Danh sách phòng ban : '.$user->department->name.' ('.$users->count().')',
        'data' => $users
       ]);
    }
    
    public function export() 
    {
        return Excel::download(new UsersExport, 'Danh_sach_users.xlsx');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.main')
@section('css')
    <style>
        .wapper {
            margin: 0 50px;
        }
    </style>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="">Home</a></li>
    <li class="breadcrumb-item active"><a href="{{ route('user.index') }}">List User</a></li>
    <li class="breadcrumb-item active">Create User</li>
@endsection

@section('content')
    <div class="wapper">
        @include('layouts.alert')
        <form action="{{ route('user.store') }}" method="post">
            @csrf
            @include('layouts.label_form', [
                'label' => 'Fulle Name',
                'name' => 'name',
                'placeholder' => 'Mời bạn nhập Tên ...',
                'value' => old('name'),
            ])

            @include('layouts.label_form', [
                'label' => 'User',
                'name' => 'user',
                'placeholder' => 'Mời bạn nhập User ...',
                'value' => old('user'),
            ])

            @include('layouts.label_form', [
                'label' => 'Email',
                'name' => 'email',
                'placeholder' => 'Mời bạn nhập Email ...',
                'value' => old('email'),
            ])

            <div class="form-group">
                <label for="">Giới tính</label> &elinters;
                <input type="radio" name="gender" checked value="0">Nam
                <input type="radio" name="gender" value="1">Nữ
            </div>

            @include('layouts.select_form', [
                'label' => 'Department',
                'name' => 'department_id',
                'data' => $data['departments'],
            ])

            @include('layouts.select_form', [
                'label' => 'Position',
                'name' => 'position_id',
                'data' => $data['positions'],
            ])

            @include('layouts.select_form', [
                'label' => 'Role',
                'name' => 'role_id',
                'data' => $data['roles'],
            ])

            @include('layouts.label_form', [
                'label' => 'Address',
                'name' => 'address',
                'placeholder' => 'Mời bạn nhập địa chỉ ...',
                'value' => old('address'),
            ])

            <div class="form-group">
                <label for="">Tình trạng</label> &elinters;
                <input type="radio" name="action" checked value="0">Dang làm
                <input type="radio" name="action" value="1">Nghỉ làm
            </div>

            @include('layouts.label_form', [
                'label' => 'Password',
                'name' => 'password',
                'type' => 'password',
                'placeholder' => 'Mời bạn nhập Password ...',
            ])

            @include('layouts.label_form', [
                'label' => 'Re-password',
                'name' => 'confirm_password',
                'type' => 'password',
                'placeholder' => 'Mời bạn nhập lại Password ...',
            ])
            <button type="submit" name="addUser" class="btn btn-success">ADD User</button>
        </form>
    </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.main')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active">Danh sách User</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-9 ">  
            <form action="" method="get">
                <input type="text" name="search" value="" placeholder="Nhập tên cần tìm...">
                <select style="padding: 3px" name="action">
                    <option value="" @selected(request()->status == null)>Tất cả</option>
                    <option value="0" @selected(request()->action == 0)>active</option>
                    <option value="1" @selected(request()->action == 1)>off</option>
                </select>
                <button type="submit" class="btn btn-sm btn-primary" name="">Tìm kiếm</button>
            </form> &ensp;
            
        </div>
        <div class="col-3">
            <a href="{{ route('export') }}" class="btn btn-sm btn-success">Xuất file</a>
            <a href="{{ route('user.list.soft.delete') }}" class="btn btn-sm btn-danger">Danh sách xóa mềm</a>
        </div>
        <div class="col-8"> @include('layouts.alert')</div>
        <table class="table table-light">
            <thead class="thead-light">
                <tr>
                    <th>STT</th>
                    <th>Full Name</th>
                    <th>User</th>
                    <th>Giới tính</th>
                    <th>Phòng ban</th>
                    <th>Vị trí</th>
                    <th>Loại tài khoản</th>
                    <th>Tình trạng</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $user)
                    <tr>
                        <td>{{ ((request()->page ?? 1) - 1) * $offset + $key + 1 }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->user }}</td>
                        <td>{{ $user->gender == 0 ? 'Nam' : 'Nữ' }}</td>
                        <td>{{ $user->department->name }}</td>
                        <td>{{ $user->position->name }}</td>
                        <td>{{ $user->role->name }}</td>
                        <td>
                            <span
                                class="badge badge-{{ $user->action == 0 ? 'success' : 'danger' }}">{{ $user->action == 0 ? 'active' : 'off' }}
                            </span>
                        </td>
                        <td>
                            <div class="row">
                                <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning"><i
                                        class="fa fa-edit"></i></a> &ensp;
                                <form action="{{ route('user.destroy', $user->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                        <i class="fa fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        <div>
            {!! $data->appends(request()->all())->links() !!}
        </div>
    </div>
@endsection

resources/views/admin/users/list_delete.blade.php
@extends('layouts.main')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active"><a href="{{ route('user.index') }}">Danh sách User</a></li>
    <li class="breadcrumb-item active">Danh sách User đã xóa</li>
@endsection

@section('content')
    @include('layouts.alert')
    <table class="table table-light">
        <thead class="thead-light">
            <tr>
                <th width= "10%">STT</th>
                <th>Full Name</th>
                <th>User</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $key => $user)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->user }}</td>
                    <td>
                        <div class="row">
                            <a href="{{ route('user.restore', $user->id) }}"  onclick="return confirm('Are you sure ?')" class="btn btn-warning"><i class="fa fa-undo"></i></a> &ensp;
                            <form action="{{ route('user.delete.over', $user->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">
                                    <i class="fa fa-trash"></i></button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach

        </tbody>

    </table>
@endsection

resources/views/admin/users/update.blade.php
@extends('layouts.main')
@section('css')
    <style>
        .wapper {
            margin: 0 50px;
        }
    </style>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('user.index') }}">User</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('content')
    <div class="wapper">
        @include('layouts.alert')
        <form action="{{ route('user.update', $user->id) }}" method="post">
            @csrf
            @method('put')
            <input type="hidden" value="{{ $user->id }} " name="id">
            @include('layouts.label_form', [
                'label' => 'Fulle Name',
                'name' => 'name',
                'placeholder' => 'Mời bạn nhập Tên ...',
                'value' => $user->name,
            ])

            @include('layouts.label_form', [
                'label' => 'User',
                'name' => 'user',
                'placeholder' => 'Mời bạn nhập User ...',
                'value' => $user->user,
                'atribute' => 'readonly',
            ])

            @include('layouts.label_form', [
                'label' => 'Email',
                'name' => 'email',
                'placeholder' => 'Mời bạn nhập Email ...',
                'value' => $user->email,
            ])

            <div class="form-group">
                <label for="">Giới tính</label> &elinters;
                <input type="radio" name="gender" {{ Auth::user()->gender == 0 ? 'checked' : '' }} value="0">Nam
                <input type="radio" name="gender" {{ Auth::user()->gender == 1 ? 'checked' : '' }} value="1">Nữ
            </div>

        
            @include('layouts.select_form', [
                'label' => 'Department',
                'name' => 'department_id',
                'data' => $data['departments'],
                'id' => $user->department->id
            ])

            @include('layouts.select_form', [
                'label' => 'Pepartment',
                'name' => 'position_id',
                'data' => $data['positions'],
                'id' => $user->position->id
            ])

            @include('layouts.select_form', [
                'label' => 'Role',
                'name' => 'role_id',
                'data' => $data['roles'],
                'id' => $user->role->id
            ])     

            @include('layouts.label_form', [
                'label' => 'Address',
                'name' => 'address',
                'placeholder' => 'Mời bạn nhập địa chỉ ...',
                'value' => $user->address,
            ])

            <div class="form-group">
                <label for="">Tình trạng</label> &elinters;
                <input type="radio" name="action" {{ Auth::user()->action == 0 ? 'checked' : '' }} value="0">Đang
                làm
                <input type="radio" name="action" {{ Auth::user()->action == 1 ? 'checked' : '' }} value="1">Nghỉ
                làm
            </div>

            @include('layouts.label_form', [
                'label' => 'Password',
                'name' => 'password',
                'type' => 'password',
                'value' => '',
                'placeholder' => 'Mời bạn nhập Password ...',
            ])

            @include('layouts.label_form', [
                'label' => 'Re-password',
                'name' => 'confirm_password',
                'type' => 'password',
                'value' => '',
                'placeholder' => 'Mời bạn nhập lại Password ...',
            ])
            <button type="submit" name="addUser" class="btn btn-success">Edit User</button>
        </form>
    </div>
    </div>
@endsection

resources/views/admin/users/view_user.blade.php
@extends('layouts.main')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active">Danh sách User</li>
@endsection

@section('content')

        <div class="col-8"> @include('layouts.alert')</div>
        <table class="table table-light">
            <tr>
                <th>STT</th>
                <th>User</th>
                <th>Giới tính</th>
                <th>Email</th>
                <th>Phòng ban</th>
                <th>Vị trí</th>
                <th>Loại tài khoản</th>
                <th>Tình trạng</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $user)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $user->user }}</td>
                        <td>{{ $user->gender == 0 ? 'Nam' : 'Nữ' }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->department->name }}</td>
                        <td>{{ $user->position->name }}</td>
                        <td>{{ $user->role->name }}</td>
                        <td>
                            <span
                                class="badge badge-{{ $user->action == 0 ? 'success' : 'danger' }}">{{ $user->action == 0 ? 'active' : 'off' }}
                            </span>
                        </td>
                        <td>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

   
@endsection