routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login',[AuthController::class, 'login'])->name('login');
Route::get('forgot_password',[AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::post('login/logon',[AuthController::class, 'logon'])->name('logon');
Route::get('logout',[AuthController::class, 'logout'])->name('logout');
Route::put('first_login',[AuthController::class, 'firstLogin'])->name('first.login');
Route::get('changePassword',[AuthController::class, 'changerPassword'])->name('change.password');
Route::put('changedPassword',[AuthController::class, 'changedPassword'])->name('changed.password');
Route::get('login/first_login',[AuthController::class, 'changedFirstLogin'])->name('form.first.login');
Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('user/List',[UserController::class, 'viewByUser'])->name('view.by.user');
    Route::middleware(['is.admin:0'])->group(function () {
        Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');
        Route::get('user/listSoftDelete',[UserController::class, 'listSoftDelete'])->name('user.list.soft.delete');
        Route::get('user/restore/{id}',[UserController::class, 'restore'])->name('user.restore');
        Route::delete('user/deleteOver/{id}',[UserController::class, 'deleteOver'])->name('user.delete.over');
        Route::resource('user',UserController::class);
        Route::resource('role',RoleController::class);
        Route::resource('position',PositionController::class);
        Route::resource('department',DepartmentController::class);
    }); 
});

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;
    protected $table = 'positions';
    public $timestamps = false;
    protected $fillable = [
        'name',
        'pority',
    ];
    
    public function users(){
        return $this->hasMany(User::class, 'position_id', ' id');
    }
}

app/Http/Controllers/PositionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Position\StorePositionRequest;
use App\Http\Requests\Position\UpdatePositionRequest;
use App\Models\Position;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $position;
    public function __construct(Position $position)
    {
        $this->position= $position;
    }
    public function index()
    {
        $data = $this->position->orderby('pority','ASC')->get();
        return view('admin.positions.index',[
            'title' => 'Danh sách chức vụ',
            'topTitle' => 'Danh sách chức vụ',
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.positions.create',[
            'title' => 'Create position',
            'toptitle' => 'Tạo chức vụ',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePositionRequest $request)
    {
        if($this->position->create($request->all())) {
            return redirect(route('position.index'))->with('success', 'Tạo thành công chức vụ : '. $request->name);
        }     
        return redirect()->back()->with('error', 'Có lỗi trong quá trình tạo');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function show(Position $position)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $position = $this->position->find($id);
        return view('admin.positions.update',[
            'title' => 'Edit Position ',
            'toptitle' => 'Sửa chức vụ :'.$position->name,
            'position' => $position
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePositionRequest $request,$id)
    {
        if($this->position->find($id)->update($request->all())) {
            return redirect(route('position.index'))->with('success', 'Sửa thành công phòng ban : '. $request->name);
        }     
        return redirect()->back()->with('error', 'Có lỗi trong quá trình Sửa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $this->position->find($id)->delete();
        return redirect()->back()->with('success', 'Xóa thành công');
    }
}

resources/views/admin/positions/create.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('position.index') }}">Position</a></li>
    <li class="breadcrumb-item active">Create</li>
@endsection

@section('content')
    @include('layouts.alert')
    <form action="{{ route('position.store') }}" method="post">
        @csrf
        @include('layouts.label_form', [
            'label' => 'Position Name',
            'name' => 'name',
            'placeholder' => 'Mời bạn nhập Tên Position ...',
            'value' => old('name'),
        ])
         @include('layouts.label_form', [
            'label' => 'Pority',
            'name' => 'pority',
            'placeholder' => 'Số càng nhỏ ưu tiên càng cao ',
            'value' => old('name'),
        ])
        <button type="submit" name="addPosition" class="btn btn-primary">Thêm Position</button>
    </form>
@endsection

resources/views/admin/positions/index.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item active">Position</li>
@endsection

@section('content')
    <div>
        @include('layouts.alert')
        <table class="table table-light table-hover">
            <thead class="thead-light">
                <tr>
                    <th width=5%>STT</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $key => $position)
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $position->name }}</td>
                        <td>
                            <div class="row">
                                <a href="{{ route('position.edit', $position->id) }}" class="btn btn-warning"><i
                                        class="fa fa-edit"></i></a> &ensp;
                                <form action="{{ route('position.destroy', $position->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">
                                        <i class="fa fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/admin/positions/update.blade.php
@extends('layouts.main')
@section('css')
@endsection

@section('js')
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
    <li class="breadcrumb-item "><a href="{{ route('position.index') }}">Position</a></li>
    <li class="breadcrumb-item active">Update</li>
@endsection

@section('content')
    <form action="{{ route('position.update', $position->id) }}" method="post">
        @csrf
        @method('put')
        @include('layouts.label_form', [
            'label' => 'Position Name',
            'name' => 'name',
            'placeholder' => 'Mời bạn nhập Tên Position ...',
            'value' => $position->name,
        ])
        @include('layouts.label_form', [
            'label' => 'Pority',
            'name' => 'pority',
            'placeholder' => 'Số càng nhỏ ưu tiên càng cao...',
            'value' => $position->pority,
        ])
        <button type="submit" name="editPosition" class="btn btn-primary">Sửa Position</button>
    </form>
@endsection