routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('login',[AuthController::class, 'login'])->name('login');
Route::get('forgot_password',[AuthController::class, 'forgotPassword'])->name('forgot.password');
Route::post('forgot_password/check_email',[AuthController::class, 'checkEmail'])->name('check.email');
Route::post('login/logon',[AuthController::class, 'logon'])->name('logon');
Route::get('logout',[AuthController::class, 'logout'])->name('logout');
Route::put('first_login',[AuthController::class, 'firstLogin'])->name('first.login');
Route::get('changePassword',[AuthController::class, 'changerPassword'])->name('change.password');
Route::put('changedPassword',[AuthController::class, 'changedPassword'])->name('changed.password');
Route::get('login/first_login',[AuthController::class, 'changedFirstLogin'])->name('form.first.login');
Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');

Route::prefix('dashboard')->middleware(['auth','first.login'])->group(function () {
    Route::get('/',[AuthController::class, 'index'])->name('dashboard');
    Route::get('user/List',[UserController::class, 'viewByUser'])->name('view.by.user');
    Route::middleware(['is.admin:0'])->group(function () {
        Route::get('dashboard/user-export',[UserController::class, 'export'])->name('export');
        Route::get('user/listSoftDelete',[UserController::class, 'listSoftDelete'])->name('user.list.soft.delete');
        Route::get('user/restore/{id}',[UserController::class, 'restore'])->name('user.restore');
        Route::delete('user/deleteOver/{id}',[UserController::class, 'deleteOver'])->name('user.delete.over');
        Route::resource('user',UserController::class);
        Route::resource('role',RoleController::class);
        Route::resource('position',PositionController::class);
        Route::resource('department',DepartmentController::class);
    }); 
});

resources/views/layouts/alert.blade.php
{{--Thong báo lỗi--}}
<div style="padding-top: 0.5rem ">
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(Session::has('error'))
    <div class="alert alert-danger">
        {{Session::get('error')}}
    </div>
@endif
@if(Session::has('success'))
    <div class="alert alert-success">
        {{Session::get('success')}}
    </div>
@endif

</div>

resources/views/layouts/breadcrumb.blade.php
<li class="breadcrumb-item"><a href="">Home</a></li>
<li class="breadcrumb-item active">Dashboard v1</li>

resources/views/layouts/content_header.blade.php
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        @if (strpos(url()->full(), 'user'))
                            <a href="{{ route('user.create') }}">
                                <h5>
                                    <i class=" fa fa-thin fa-user"></i> <span class="action">Create User</span>
                                </h5>
                            </a>
                        @endif
                        <p>User</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{{ route('user.index') }}" class="small-box-footer">View List <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        @if (strpos(url()->full(), 'department'))
                            <a href="{{ route('department.create') }}">
                                <h5>
                                    <i class="fa fa-building"></i> <span class="action">Create Department</span>
                                </h5>
                            </a>
                        @endif
                        <p>Departments</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{{ route('department.index') }}" class="small-box-footer">View List <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        @if (strpos(url()->full(), 'position'))
                            <a href="{{ route('position.create') }}">
                                <h5>
                                    <i class="fa fa-horse"></i>  <span class="action">Create Position</span>
                                </h5>
                            </a>
                        @endif
                        <p>Positions</p> 
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="{{  route('position.index') }}" class="small-box-footer">View List <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        @if (strpos(url()->full(), 'role'))
                            <a href="{{ route('role.create') }}">
                                <h5>
                                    <i class="fa fa-scroll"></i>  <span class="action">Create Role</span>
                                </h5>
                            </a>
                        @endif
                        <p>Roles</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="{{  route('role.index') }}" class="small-box-footer">View List<i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
    </div><!-- /.container-fluid -->
</section>

resources/views/layouts/input.blade.php
<input type="{{ $type ?? 'text' }}" name="{{ $name ? '' }}" id="{{ $id  ?? ''}}">

resources/views/layouts/label_form.blade.php
     <div class="form-group">
         <label for="">{{ $label ?? 'Label' }}</label>
         <input type="{{ $type ?? 'text' }}" {{ $atribute ?? "" }}   class="{{ $class ?? 'form-control' }}" attt value="{{ $value ?? '' }}"
             name="{{ $name ?? '' }}" placeholder="{{ $placeholder ?? '' }}">
         @error($name)
             <span class=" text-danger">{{ $message }}</span>
         @enderror
     </div>

resources/views/layouts/select_form.blade.php
<div class="form-group">
    <label for="{{ $name ?? 'name' }}">{{ $label ?? 'name' }}</label>
    <select class="form-control" required name="{{ $name ?? 'name' }}" id="{{ $name ?? 'name' }}">
        <option value="">---Chọn {{ $label }}---</option>
        @foreach ($data as $item)
            <option value="{{ $item->id }}" {{ isset($id) && $id == $item->id ? 'selected' : '' }}>
                {{ $item->name }}</option>
        @endforeach
    </select>
    @error($name)
        <span class=" text-danger">{{ $message }}</span>
    @enderror
</div>